# This is a basic workflow to help you get started with Actions

name: upload-artifact
run-name: upload-artifact to ${{ inputs.deploy_target }} by @${{ github.actor }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  d1d2: "${{github.workspace}}\\d1\\d2"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Create some files
      - name: Run a one-line script
        run: |
          mkdir d1
          cd d1
          mkdir d2
          cd d2
          echo f1 > f1.txt
          echo f2 > f2.txt
          echo l1 > l1.log
          echo l2 > l2.log
          cd ..\..

      - name: echo and dir d1d2_?
        run: |
          echo ${{env.d1d2}}
          dir ${{env.d1d2}}
          dir d1\d2
          dir ${{github.workspace}}\\d1\d2

      # upload-artifact
      - name: upload-1
        uses: actions/upload-artifact@v4
        with:
          name: upload-1.zip
          path: |
            d1\d2\f1.txt
            d1\d2\f2.txt
            d1\d2\l?.log

      - name: upload-2
        uses: actions/upload-artifact@v4
        with:
          name: upload-2.zip
          path: |
            ${{github.workspace}}\d1\d2\f1.txt
            ${{github.workspace}}\d1\d2\f2.txt
            ${{github.workspace}}\d1\d2\l?.log
